config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :accounts
    resources :iaa_gtcs
    resources :iaa_orders
    resources :integrations
    resources :integration_usages
    resources :users
    resources :account_contacts, only: %i[index show new create destroy]
    resources :integration_contacts, only: %i[index show new create destroy]
    resources :agencies
    resources :account_statuses
    resources :iaa_statuses
    resources :integration_statuses

    root to: "accounts#index"
  end

  devise_for :users, skip: [:sessions]

  devise_scope :user do
    get '/users/logout' => 'users/sessions#destroy', as: :destroy_user_session
    get 'active'  => 'users/sessions#active'
    get 'timeout' => 'users/sessions#timeout'
  end

  get '/auth/logindotgov/callback' => 'users/omniauth#callback'

  resources :accounts, only: [:index, :show]

  root to: 'home#index'
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this
# `Administrate::ApplicationController`, making it the ideal place to put
# authentication logic or other before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController

    helper :assets

    before_action :authenticate_admin

    def authenticate_admin
      authenticate_user!
      return if current_user.admin?
      flash[:warning] = 'You are not permitted to view that page.'
      redirect_to root_path
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :render_401

  def new_session_path(_scope)
    root_url
  end

  def render_401
    render file: 'public/401.html', status: :unauthorized
  end
end

app/views/application/_demo_banner.html.erb
<section class="usa-banner" aria-label="Test site">
  <header class="usa-banner__header secondary">
    <div class="usa-banner__inner">
      <div class="grid-col-fill tablet:grid-col-auto">
        <p class="usa-banner__header-text">TEST SITE - Do not use any real information (demo purposes only) - TEST SITE</p>
      </div>
    </div>
  </header>
</section>

app/views/application/_flashes.html.erb
<% user_facing_flashes.each do |name, msg| %>
  <div class="usa-alert usa-alert--<%= name %>">
    <div class="usa-alert__body">
      <p class="usa-alert__text"><%= msg %></p>
    </div>
  </div>
<% end %>

app/views/application/_usa_banner.html.erb
<div class="usa-banner">
  <div class="usa-accordion">
    <header class="usa-banner__header">
      <div class="usa-banner__inner">
        <div class="grid-col-auto">
          <%= image_tag identity_asset_path('img/us_flag_small.png'), class: 'usa-banner__header-flag', alt: 'U.S. flag' %>
        </div>
        <div class="grid-col-fill tablet:grid-col-auto">
          <p class="usa-banner__header-text">An official website of the United States government</p>
          <p class="usa-banner__header-action" aria-hidden="true">Here’s how you know</p>
        </div>
        <button class="usa-accordion__button usa-banner__button" aria-expanded="false" aria-controls="gov-banner">
          <span class="usa-banner__button-text">Here’s how you know</span>
        </button>
      </div>
    </header>
    <div class="usa-banner__content usa-accordion__content" id="gov-banner" hidden="">
      <div class="grid-row grid-gap-lg">
        <div class="usa-banner__guidance tablet:grid-col-6">
          <%= image_tag identity_asset_path('img/icon-dot-gov.svg'), class: 'usa-banner__icon usa-media-block__img', alt: 'Dot gov' %>
          <div class="usa-media-block__body">
            <p>
              <strong>The .gov means it’s official.</strong>
              <br>
              Federal government websites often end in .gov or .mil. Before sharing sensitive information, make sure you’re on a federal government site.
            </p>
          </div>
        </div>
        <div class="usa-banner__guidance tablet:grid-col-6">
          <%= image_tag identity_asset_path('img/icon-https.svg'), class: 'usa-banner__icon usa-media-block__img', alt: 'Https' %>
          <div class="usa-media-block__body">
            <p>
              <strong>The site is secure.</strong>
              <br>
              The <strong>https://</strong> ensures that you are connecting to the official website and that any information you provide is encrypted and transmitted securely.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/application/_usa_footer.html.erb
<footer class="usa-footer usa-footer--slim" role="contentinfo">
  <div class="grid-container usa-footer__return-to-top">
    <div class="grid-row flex-align-center">
      <div class="grid-col flex-1">
        <a href="#">Return to top</a>
      </div>
    </div>
  </div>
  <div class="usa-footer__secondary-section">
    <div class="grid-container">
      <div class="usa-footer__logo grid-row grid-gap-2">
        <div class="grid-col-auto">
          <%= image_tag identity_asset_path('img/gsa-logo-rev.svg'), class: 'usa-footer__logo-img usa-footer__slim usa-footer__medium', alt: 'U.S. General Services Administration logo' %>
        </div>
        <div class="grid-col-auto">
          <h3 class="usa-footer__logo-heading">U.S. General Services Administration</h3>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/application/_usa_header.html.erb
<header class="usa-header usa-header--basic" role="banner">
  <div class="usa-nav-container">
    <div class="usa-navbar">
      <div class="usa-logo" id="basic-logo">
        <%= link_to root_path, title: 'Home', aria: { label: 'Home' } do %>
          <%= image_tag identity_asset_path('img/login-gov-logo.svg'), class: 'usa-logo__img', alt: 'login.gov' %>
          <em class="usa-logo__text">Account Console</em>
      <% end %>
      </div>
      <button class="usa-menu-btn">Menu</button>
    </div>
    <nav role="navigation" class="usa-nav">
      <button class="usa-nav__close"><%= image_tag identity_asset_path('img/close.svg'), alt: 'Close' %></button>
      <ul class="usa-nav__primary usa-accordion">
        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <li class="usa-nav__primary-item">
              <button class="usa-accordion__button usa-nav__link" aria-controls="header-admin-submenu" aria-expanded="false">
                <span>Admin</span>
              </button>
              <ul id="header-admin-submenu" class="usa-nav__submenu" hidden="">
                <li class="usa-nav__submenu-item">
                  <%= link_to accounts_path do %>
                    <span>Accounts</span>
                  <% end %>
                  </a>
                </li>
                <li class="usa-nav__submenu-item">
                  <%= link_to admin_root_path do %>
                    <span>Admin Dashboard</span>
                  <% end %>
                </li>
              </ul>
            </li>
          <% end %>
          <li class="usa-nav__primary-item">
            <%= link_to destroy_user_session_path, class: 'usa-nav__link' do %>
              <span>Sign out</span>
            <% end %>
          </li>
        <% else %>
          <li class="usa-nav__primary-item">
            <%= link_to '/auth/logindotgov', data: { method: 'post' }, class: 'usa-nav__link' do %>
              <span>Sign in</span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>