config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :accounts
    resources :iaa_gtcs
    resources :iaa_orders
    resources :integrations
    resources :integration_usages
    resources :users
    resources :account_contacts, only: %i[index show new create destroy]
    resources :integration_contacts, only: %i[index show new create destroy]
    resources :agencies
    resources :account_statuses
    resources :iaa_statuses
    resources :integration_statuses

    root to: "accounts#index"
  end

  devise_for :users, skip: [:sessions]

  devise_scope :user do
    get '/users/logout' => 'users/sessions#destroy', as: :destroy_user_session
    get 'active'  => 'users/sessions#active'
    get 'timeout' => 'users/sessions#timeout'
  end

  get '/auth/logindotgov/callback' => 'users/omniauth#callback'

  resources :accounts, only: [:index, :show]

  root to: 'home#index'
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :account_status, optional: true
  belongs_to :agency

  has_many :account_contacts, dependent: :destroy
  has_many :contacts, through: :account_contacts, source: :user
  has_many :iaa_gtcs, dependent: :destroy
  has_many :iaa_orders, through: :iaa_gtcs
  has_many :integrations, dependent: :destroy

  validates :lg_identifier, presence: true,
                            uniqueness: { case_sensitive: false }
  validates :name, presence: true
end

app/controllers/accounts_controller.rb
class AccountsController < AuthenticatedController

  def index
    if current_user.admin?
      @accounts = Account.all
    else
      @accounts = current_user.accounts
    end
  end

  def show
    @account ||= Account.find(params[:id])
  end
end

app/controllers/admin/accounts_controller.rb
module Admin
  class AccountsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/views/accounts/_my_account.html.erb
<div class="usa-display"><%= @account.name %></div>
<p class="usa-intro"><%= @account.lg_identifier %></p>

<h2 id="contacts">Contacts</h2>
<% if @account.account_contacts.count.positive? %>
  <table class="usa-table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Title</th>
        <th scope="col">Email</th>
        <th scope="col">Phone</th>
      </tr>
    </thead>
    <tbody>
      <% @account.account_contacts.each do |ac| %>
        <tr>
          <td><%= "#{ac.user.first_name} #{ac.user.last_name}" %></td>
          <td><%= ac.user.title %></td>
          <td><%= ac.user.email %></td>
          <td><%= ac.user.phone %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No contacts found.</p>
<% end %>

<h2 id="agreements">IAA funds</h2>
<% if @account.iaa_gtcs.count.positive? %>
  <table class="usa-table">
    <thead>
      <tr>
        <th scope="col">GT&amp;C (7600A)</th>
        <th scope="col">Start date</th>
        <th scope="col">End date</th>
        <th scope="col">Amount</th>
        <th scope="col">Billed</th>
        <th scope="col">Remaining</th>
      </tr>
    </thead>
    <tbody>
      <% @account.iaa_gtcs.each do |iaa_gtc| %>
        <tr>
          <td><%= iaa_gtc.name %></td>
          <td><%= iaa_gtc.start_date %></td>
          <td><%= iaa_gtc.end_date %></td>
          <td><%= number_to_currency(iaa_gtc.estimated_amount, precision: 0) %></td>
          <td>Coming Soon</td>
          <td>Coming Soon</td>
        </tr>
      <% end %>
    </tbody>
    <% if @account.iaa_orders.count.positive? %>
      <thead>
        <tr>
          <th scope="col">Order (7600B)</th>
          <th scope="col">Start date</th>
          <th scope="col">End date</th>
          <th scope="col">Amount</th>
          <th scope="col">Cost to Date</th>
          <th scope="col">Remaining</th>
        </tr>
      </thead>
      <tbody>
        <% @account.iaa_orders.each do |iaa_order| %>
          <tr>
            <td><%= iaa_order.name %></td>
            <td><%= iaa_order.start_date %></td>
            <td><%= iaa_order.end_date %></td>
            <td><%= number_to_currency(iaa_order.estimated_amount, precision: 0) %></td>
            <td><%= number_to_currency(iaa_order.cost_to_date, precision: 2) %></td>
            <td><%= number_to_currency(iaa_order.estimated_amount - iaa_order.cost_to_date, precision: 2) %></td>
          </tr>
        <% end %>
      </tbody>
    <% else %>
      <thead>
        <tr>
          <th rowspan="6">No IAA Orders found.</th>
        </tr>
      </thead>
    <% end %>
  </table>
<% else %>
  <p>No IAA's found.</p>
<% end %>

<h2 id="integrations">Integrations</h2>
<% if @account.integrations.count.positive? %>
  <table class="usa-table margin-bottom-4 width-full">
    <% @account.integrations.each do |integration| %>
      <thead>
        <tr>
          <th scope="col" colspan="5" style="font-size:1.2rem"><%= integration.name %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td colspan="5"><%= integration.description %></td>
        </tr>
      </tbody>
      <thead>
        <tr>
          <th scope="col">URL</th>
          <th scope="col">IAL2</th>
          <th scope="col">Status</th>
          <th scope="col">Go live</th>
          <th scope="col">Prod deploy</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= link_to integration.url, integration.url, target: '_blank' %></td>
          <td><%= integration.ial2 %></td>
          <td><%= integration.integration_status.partner_name.titleize %></td>
          <td><%= integration.go_live %></td>
          <td><%= integration.prod_deploy %></td>
        </tr>
      </tbody>
    <% end %>
  </table>
<% else %>
  <p>No Integrations found.</p>
<% end %>

app/views/accounts/index.html.erb
<div class="usa-display">Accounts</div>

<table class="usa-table">
  <thead>
    <tr>
      <th scope="col">Account ID</th>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
    </tr>
  </thead>
  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= link_to account.lg_identifier, account_path(account), class: 'text-bold' %></td>
        <td><%= account.name %></td>
        <td><%= account.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/accounts/show.html.erb
<%= render 'my_account' %>